# Generated by Django 5.0.1 on 2024-03-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
