# Generated by Django 4.2.3 on 2023-11-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='OrphanBehavior_notes',
        ),
    ]
