# Generated by Django 4.2.3 on 2023-11-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_alter_notes_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='orphan_id',
        ),
    ]
