# Generated by Django 4.2.3 on 2023-11-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('< 18.5', 'Underweight'), ('18.5 - 24.9', 'Normal Weight'), ('25 - 29.9', 'Overweight'), ('30 or more', 'Obesity')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileDescription', models.TextField(blank=True, null=True)),
                ('filePath', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'orphan_files',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Accident', 'Accident'), ('Illness', 'Illness'), ('Injury', 'Injury'), ('Other', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('orphanID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('middleName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('dateAdmitted', models.DateField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('orphan_picture', models.ImageField(upload_to='orphan_pictures/')),
                ('orphanFileID', models.ForeignKey(db_column='orphanFileID', on_delete=django.db.models.deletion.PROTECT, to='orphans.files')),
            ],
            options={
                'db_table': 'orphan_infos',
            },
        ),
        migrations.CreateModel(
            name='PhysicalHealth',
            fields=[
                ('healthID', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incident_count', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateField(blank=True, null=True)),
                ('bmi_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orphans.bmicategory')),
                ('incident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orphans.incidenttype')),
                ('orphan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='physical_health', to='orphans.info')),
            ],
            options={
                'db_table': 'orphan_health',
            },
        ),
    ]
