# Generated by Django 5.0.3 on 2024-04-05 03:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_dob', models.DateField(blank=True, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_address', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_status', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_dob', models.DateField(blank=True, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('father_address', models.CharField(blank=True, max_length=255, null=True)),
                ('father_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'family_infos',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(blank=True, max_length=255, null=True)),
                ('fileDescription', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'general_files',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Accident', 'Accident'), ('Illness', 'Illness'), ('Injury', 'Injury'), ('Other', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('orphanID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('middleName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('dateAdmitted', models.DateField(blank=True, null=True)),
                ('orphan_picture', models.ImageField(blank=True, null=True, upload_to='orphan_pictures/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Admitted'), ('G', 'Graduated')], default='P', max_length=1)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphans.family')),
            ],
            options={
                'db_table': 'orphan_infos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEducation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College')], max_length=20, null=True)),
                ('school_name', models.CharField(max_length=255)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('date_recorded', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orphan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orphans.info')),
            ],
            options={
                'verbose_name': 'historical education',
                'verbose_name_plural': 'historical educations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBMI',
            fields=[
                ('bmi_ID', models.IntegerField(blank=True, db_index=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incident_count', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, editable=False)),
                ('bmi_category', models.CharField(blank=True, choices=[('< 18.5', 'Underweight'), ('18.5 - 24.9', 'Normal Weight'), ('25 - 29.9', 'Overweight'), ('30 or more', 'Obese')], max_length=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orphans.incidenttype')),
                ('orphan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orphans.info')),
            ],
            options={
                'verbose_name': 'historical bmi',
                'verbose_name_plural': 'historical bmis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HealthDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('blood_pressure', models.CharField(max_length=7)),
                ('heart_rate', models.IntegerField()),
                ('nausea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('stomachache', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_details', to='orphans.info')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College')], max_length=20, null=True)),
                ('school_name', models.CharField(max_length=255)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='orphans.info')),
            ],
        ),
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('bmi_ID', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incident_count', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bmi_category', models.CharField(blank=True, choices=[('< 18.5', 'Underweight'), ('18.5 - 24.9', 'Normal Weight'), ('25 - 29.9', 'Overweight'), ('30 or more', 'Obese')], max_length=20, null=True)),
                ('incident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orphans.incidenttype')),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_health', to='orphans.info')),
            ],
            options={
                'db_table': 'orphan_BMI',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('translated_note', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orphans.info')),
            ],
            options={
                'db_table': 'OrphanBehavior_notes',
            },
        ),
        migrations.CreateModel(
            name='OrphanFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orphan_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('type_of_document', models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Identification', 'Identification'), ('Medical Certificates', 'Medical Certificates'), ('Grade Cards', 'Grade Cards'), ('Other Documents', 'Other Documents')], max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphan_files', to='orphans.info')),
            ],
            options={
                'db_table': 'orphan_files',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)])),
                ('quarter', models.IntegerField(blank=True, choices=[(1, 'First Quarter'), (2, 'Second Quarter'), (3, 'Third Quarter'), (4, 'Fourth Quarter')], null=True)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester')], null=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphans.education')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphans.subject')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='subjects',
            field=models.ManyToManyField(through='orphans.Grade', to='orphans.subject'),
        ),
    ]
