# Generated by Django 4.2.3 on 2023-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='orphan_picture',
            field=models.ImageField(blank=True, null=True, upload_to='orphan_pictures/'),
        ),
    ]
