# Generated by Django 4.2.3 on 2023-12-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0002_alter_info_orphan_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='filePath',
        ),
    ]
