# Generated by Django 4.2.3 on 2023-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0003_remove_files_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='orphanFileID',
        ),
        migrations.AddField(
            model_name='info',
            name='files',
            field=models.ManyToManyField(related_name='orphans', to='orphans.files'),
        ),
    ]
