# Generated by Django 5.0.3 on 2024-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0003_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='bmi_category',
            field=models.CharField(blank=True, choices=[('< 18.5', 'Underweight'), ('18.5 - 24.9', 'Normal Weight'), ('25 - 29.9', 'Overweight'), ('30 or more', 'Obesity')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbmi',
            name='bmi_category',
            field=models.CharField(blank=True, choices=[('< 18.5', 'Underweight'), ('18.5 - 24.9', 'Normal Weight'), ('25 - 29.9', 'Overweight'), ('30 or more', 'Obesity')], max_length=20, null=True),
        ),
    ]
