# Generated by Django 4.2.3 on 2024-01-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalhealth',
            name='bmi_category',
            field=models.CharField(blank=True, choices=[('< 18.5', 'Underweight'), ('18.5 - 24.9', 'Normal Weight'), ('25 - 29.9', 'Overweight'), ('30 or more', 'Obesity')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='BMICategory',
        ),
    ]
