# Generated by Django 5.0.3 on 2024-04-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0004_alter_bmi_bmi_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='orphans.education'),
        ),
    ]
