# Generated by Django 5.0.3 on 2024-04-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0005_alter_grade_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('academic', 'Academic'), ('behavior', 'Behavior'), ('health', 'Health')], max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='orphans.info')),
            ],
        ),
    ]
