# Generated by Django 5.0.3 on 2024-04-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0006_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('unresolved', 'Unresolved')], default='pending', max_length=10),
        ),
    ]
