# Generated by Django 5.0.3 on 2024-04-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0008_remove_healthdetail_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetail',
            name='resolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
