# Generated by Django 4.2.3 on 2024-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0009_alter_education_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College')], max_length=20, null=True),
        ),
    ]
