# Generated by Django 5.0.3 on 2024-04-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0009_healthdetail_resolved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdetail',
            old_name='nausea',
            new_name='body_pain',
        ),
        migrations.RenameField(
            model_name='healthdetail',
            old_name='pain',
            new_name='fever',
        ),
    ]
