# Generated by Django 5.0.3 on 2024-04-17 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0010_rename_nausea_healthdetail_body_pain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('unresolved', 'Unresolved')], default='pending', max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='orphans.info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BehaviorIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('unresolved', 'Unresolved')], default='pending', max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='orphans.info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('unresolved', 'Unresolved')], default='pending', max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='orphans.info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
    ]
