# Generated by Django 5.0.1 on 2024-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0011_alter_info_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
