# Generated by Django 5.0.3 on 2024-04-17 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0011_academicintervention_behaviorintervention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthintervention',
            name='health_notes',
        ),
        migrations.AlterField(
            model_name='academicintervention',
            name='orphan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicinterventions', to='orphans.info'),
        ),
        migrations.AlterField(
            model_name='behaviorintervention',
            name='orphan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviorinterventions', to='orphans.info'),
        ),
        migrations.AlterField(
            model_name='healthintervention',
            name='orphan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthinterventions', to='orphans.info'),
        ),
    ]
