# Generated by Django 5.0.3 on 2024-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0012_remove_healthintervention_health_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
