# Generated by Django 5.0.1 on 2024-03-01 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0012_files_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
