# Generated by Django 5.0.3 on 2024-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0013_info_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdetail',
            name='date',
        ),
        migrations.AddField(
            model_name='healthdetail',
            name='sick_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthdetail',
            name='sick_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
