# Generated by Django 5.0.1 on 2024-03-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0014_family_remove_info_fathersname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalhealth',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterField(
            model_name='physicalhealth',
            name='orphan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_health', to='orphans.info'),
        ),
    ]
