# Generated by Django 5.0.3 on 2024-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0014_remove_healthdetail_date_healthdetail_sick_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthintervention',
            name='is_unresolved',
            field=models.BooleanField(default=False),
        ),
    ]
