# Generated by Django 5.0.3 on 2024-04-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0015_healthintervention_is_unresolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthintervention',
            name='is_unresolved',
        ),
    ]
