# Generated by Django 5.0.3 on 2024-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0016_remove_healthintervention_is_unresolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicintervention',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('unresolved', 'Unresolved'), ('none', 'None')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='behaviorintervention',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('unresolved', 'Unresolved'), ('none', 'None')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthintervention',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('unresolved', 'Unresolved'), ('none', 'None')], default='pending', max_length=10),
        ),
    ]
