# Generated by Django 5.0.1 on 2024-03-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0016_subject_grade_education_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester')], null=True),
        ),
        migrations.AddField(
            model_name='historicaleducation',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester')], null=True),
        ),
    ]
