# Generated by Django 5.0.1 on 2024-03-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0017_education_semester_historicaleducation_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='year',
        ),
    ]
