# Generated by Django 5.0.3 on 2024-05-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0018_behaviorintervention_baseline_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicintervention',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='academicintervention',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='behaviorintervention',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='behaviorintervention',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthintervention',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='healthintervention',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
