# Generated by Django 5.0.3 on 2024-05-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0019_alter_academicintervention_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicintervention',
            name='baseline_sentiment',
            field=models.FloatField(blank=True, help_text='Sentiment score at the time of resolving the intervention.', null=True),
        ),
    ]
