# Generated by Django 5.0.1 on 2024-03-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0020_notes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='OrphanBehavior_notes',
        ),
    ]
