# Generated by Django 5.0.3 on 2024-05-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0020_academicintervention_baseline_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicintervention',
            name='baseline_sentiment',
        ),
        migrations.AddField(
            model_name='academicintervention',
            name='baseline_critical',
            field=models.BooleanField(default=False, help_text='Indicates if critical improvement was needed at the time of resolving the intervention.'),
        ),
        migrations.AddField(
            model_name='academicintervention',
            name='baseline_significant',
            field=models.BooleanField(default=False, help_text='Indicates if significant improvement was needed at the time of resolving the intervention.'),
        ),
    ]
