# Generated by Django 5.0.3 on 2024-05-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0021_remove_academicintervention_baseline_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthintervention',
            name='baseline_health_score',
            field=models.FloatField(blank=True, help_text='Health score at the time of resolving the intervention.', null=True),
        ),
    ]
