# Generated by Django 5.0.1 on 2024-03-22 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0021_alter_notes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='birth_certificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to='birth_certificates/'),
            preserve_default=False,
        ),
    ]
