# Generated by Django 5.0.3 on 2024-05-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0022_healthintervention_baseline_health_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='historicaleducation',
            name='school_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
