# Generated by Django 5.0.1 on 2024-03-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0023_alter_info_birth_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
