# Generated by Django 5.0.1 on 2024-03-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0025_alter_files_file_alter_info_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='related_orphan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orphans.info'),
        ),
    ]
