# Generated by Django 5.0.1 on 2024-03-25 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0027_remove_physicalhealth_incident_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('blood_pressure', models.CharField(max_length=7)),
                ('heart_rate', models.IntegerField()),
                ('nausea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('stomachache', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('others_symptoms', models.CharField(blank=True, max_length=255, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_details', to='orphans.info')),
            ],
        ),
    ]
