# Generated by Django 5.0.1 on 2024-04-02 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0029_remove_healthdetail_others_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='related_orphan',
        ),
        migrations.AlterModelTable(
            name='files',
            table='general_files',
        ),
        migrations.CreateModel(
            name='OrphanFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orphan_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('type_of_document', models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Identification', 'Identification'), ('Medical Certificates', 'Medical Certificates'), ('Grade Cards', 'Grade Cards'), ('Other Documents', 'Other Documents')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphan_files', to='orphans.info')),
            ],
            options={
                'db_table': 'orphan_files',
            },
        ),
    ]
