# Generated by Django 5.0.1 on 2024-04-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0030_remove_files_related_orphan_alter_files_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='birth_certificate',
        ),
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Admitted')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='orphanfiles',
            name='type_of_document',
            field=models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Identification', 'Identification'), ('Medical Certificates', 'Medical Certificates'), ('Grade Cards', 'Grade Cards'), ('Other Documents', 'Other Documents')], max_length=55),
        ),
    ]
