# Generated by Django 5.0.1 on 2024-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0031_remove_info_birth_certificate_alter_info_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalbmi',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
