# Generated by Django 5.0.1 on 2024-04-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0032_bmi_bmi_historicalbmi_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalbmi',
            name='recorded_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
