# Generated by Django 5.0.1 on 2024-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0033_alter_bmi_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
